import type { Metadata } from "next";
import "./globals.css";
import "../styles/jcrop.css";
import CssBaseline from '@mui/material/CssBaseline';
import { ThemeProvider } from '../contexts/ThemeContext';
import { PlanetaryDataProvider } from '@/contexts/PlanetaryDataContext';
import { LegalProvider } from '@/contexts/LegalContent';
import Chatbot from '@/components/Chatbot';
import ClientOnly from '@/components/ClientOnly';
import ReduxProvider from '@/components/providers/ReduxProvider';
import Toast from "@/components/ui/Toast";

export const metadata: Metadata = {
  title: "Brahma Vastu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ThemeProvider>
            <CssBaseline />
            <PlanetaryDataProvider>
              <LegalProvider>
                {children}
                <ClientOnly>
                  <Chatbot />
                </ClientOnly>
              </LegalProvider>
            </PlanetaryDataProvider>
          </ThemeProvider>
        </ReduxProvider>
        <Toast />
      </body>
    </html>
  );
}