name: Deploy Brahma Vastu to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "NODE_ENV=production" >> .env
          echo "NEXT_PUBLIC_SITE_URL=https://bharmaspace.com" >> .env
          echo "NEXT_PUBLIC_API_URL=http://43.205.120.197:8000" >> .env
          echo "NEXT_PUBLIC_TWITTER_HANDLE=@divyavastu" >> .env
          echo "NEXT_PUBLIC_FACEBOOK_PAGE=https://facebook.com/divyavastu" >> .env
          echo "NEXT_PUBLIC_INSTAGRAM_PAGE=https://instagram.com/divyavastu" >> .env
          echo "NEXT_PUBLIC_SITE_NAME=Brahma Vastu" >> .env
          echo "NEXT_PUBLIC_SITE_DESCRIPTION=Professional Vastu Shastra consultation services. Get instant Vastu analysis of your floor plan, expert tips, remedies, and comprehensive guidance for your home and office." >> .env
          echo "NEXT_PUBLIC_SITE_KEYWORDS=Vastu Shastra,Vastu Consultation,Floor Plan Analysis,Home Vastu,Office Vastu,Vastu Expert,Vastu Tips,Vastu Remedies,Brahma Vastu,Vastu Analysis,Vastu Check,Vastu Services" >> .env
          echo "NEXT_PUBLIC_CONTACT_EMAIL=contact@bharmaspace.com" >> .env
          echo "NEXT_PUBLIC_COMPANY_NAME=Brahma Vastu" >> .env
          echo "NEXT_PUBLIC_COMPANY_ADDRESS=India" >> .env
          echo "NEXT_PUBLIC_COMPANY_FOUNDED=2024" >> .env

      - name: Build Docker image
        run: docker build -t rushabh046/brahma_vastu -f ./Dockerfile .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Publish Docker image
        run: docker push rushabh046/brahma_vastu:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fix Docker permissions
        run: |
          sudo chmod 666 /var/run/docker.sock || true
          sudo chown root:docker /var/run/docker.sock || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull Docker image
        run: docker pull rushabh046/brahma_vastu:latest

      - name: Delete Old Docker container
        run: docker rm -f bv-container || true

      - name: Run Docker container
        run: |
          docker run -d -p 80:3000 \
            --name bv-container \
            -e NODE_ENV=production \
            -e NEXT_PUBLIC_SITE_URL=https://bharmaspace.com \
            -e NEXT_PUBLIC_API_URL=http://43.205.120.197:8000 \
            -e NEXT_PUBLIC_TWITTER_HANDLE=@divyavastu \
            -e NEXT_PUBLIC_FACEBOOK_PAGE=https://facebook.com/divyavastu \
            -e NEXT_PUBLIC_INSTAGRAM_PAGE=https://instagram.com/divyavastu \
            -e NEXT_PUBLIC_SITE_NAME="Brahma Vastu" \
            -e NEXT_PUBLIC_SITE_DESCRIPTION="Professional Vastu Shastra consultation services. Get instant Vastu analysis of your floor plan, expert tips, remedies, and comprehensive guidance for your home and office." \
            -e NEXT_PUBLIC_SITE_KEYWORDS="Vastu Shastra,Vastu Consultation,Floor Plan Analysis,Home Vastu,Office Vastu,Vastu Expert,Vastu Tips,Vastu Remedies,Brahma Vastu,Vastu Analysis,Vastu Check,Vastu Services" \
            -e NEXT_PUBLIC_CONTACT_EMAIL=contact@bharmaspace.com \
            -e NEXT_PUBLIC_COMPANY_NAME="Brahma Vastu" \
            -e NEXT_PUBLIC_COMPANY_ADDRESS="India" \
            -e NEXT_PUBLIC_COMPANY_FOUNDED=2024 \
            rushabh046/brahma_vastu:latest
